language: php

php:
  - 5.6
  - 7.0
  - hhvm

sudo: required

services:
  - docker

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

matrix:
  fast_finish: true

before_install:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then docker build --build-args COMPOSER_OPTS=$COMPOSER_OPTS -t mamuz/phpda-php56 -f Dockerfile-php56; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then docker build --build-args COMPOSER_OPTS=$COMPOSER_OPTS -t mamuz/phpda-php70 -f Dockerfile-php70; fi
  - if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then docker build --build-args COMPOSER_OPTS=$COMPOSER_OPTS -t mamuz/phpda-hhvm -f Dockerfile-hhvm; fi

script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then docker run --rm -it mamuz/phpda-php56 ./vendor/bin/codecept run; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then docker run --rm -it mamuz/phpda-php70 ./vendor/bin/codecept run; fi
  - if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then docker run --rm -it mamuz/phpda-hhvm ./vendor/bin/codecept run; fi
