language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

sudo: required

services:
  - docker

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  - composer install --prefer-source
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then docker build -t mamuz/phpda .; fi

install:
  - travis_retry composer update $COMPOSER_OPTS

before_script:
 - mkdir -p tests/files

script:
  - if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then ./vendor/bin/phpunit; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./vendor/bin/phpunit --coverage-text --coverage-clover coverage.xml; fi
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then docker run --rm -it mamuz/phpda ./vendor/bin/codecept run; fi

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi
